"""Mirror application history into an Obsidian vault.

One note per application under <vault>/<subfolder>/. The note is split by
a marker line: everything ABOVE the marker is regenerated by jobmail on each
write; everything BELOW is yours and is preserved untouched. An index note
(_Index.md) lists every application with its stage, and is fully regenerated.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from pathlib import Path

from .db import STAGES, Database

log = logging.getLogger(__name__)

MARKER = "<!-- jobmail: everything above this line is regenerated; your notes below are preserved -->"
INDEX_NAME = "_Index.md"


def _safe_filename(s: str) -> str:
    s = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "", s)
    s = re.sub(r"\s+", " ", s).strip(" .")
    return s[:120] or "untitled"


def _fmt_dt(iso: str | None) -> str:
    if not iso:
        return ""
    try:
        return datetime.fromisoformat(iso).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return iso


def _fmt_d(iso: str | None) -> str:
    if not iso:
        return ""
    try:
        return datetime.fromisoformat(iso).strftime("%Y-%m-%d")
    except Exception:
        return iso[:10]


def _yaml_str(s: str | None) -> str:
    s = (s or "").replace('"', '\\"')
    return f'"{s}"'


class ObsidianWriter:
    def __init__(self, vault: Path, subfolder: str = "Applications"):
        self.dir = Path(vault) / subfolder

    def _ensure_dir(self) -> None:
        """Create the notes folder on first write, not at construction.

        Obsidian is an optional mirror. Building it must never be able to stop
        the poller: an unreachable vault path (a drive not mounted yet, a stale
        path in .env) should cost you notes for that run, not the mail.
        """
        self.dir.mkdir(parents=True, exist_ok=True)

    # --------------------------------------------------------------- paths
    def note_path(self, app_id: int, company: str, role: str | None) -> Path:
        base = _safe_filename(f"{company} - {role}" if role else company)
        # Stable across renames: look for an existing note tagged with this id.
        for p in (self.dir.glob("*.md") if self.dir.is_dir() else []):
            if p.name == INDEX_NAME:
                continue
            try:
                head = p.read_text(encoding="utf-8")[:400]
            except Exception:
                continue
            if f"jobmail_id: {app_id}\n" in head:
                return p
        path = self.dir / f"{base}.md"
        n = 2
        while path.exists():
            path = self.dir / f"{base} ({n}).md"
            n += 1
        return path

    # --------------------------------------------------------------- render
    def render_application(self, db: Database, app_id: int) -> str:
        app = db.get_application(app_id)
        assert app is not None
        msgs = db.list_messages_for_application(app_id)
        events = db.list_events(app_id)
        dates = db.list_key_dates_for_application(app_id)
        domains = json.loads(app["sender_domains"] or "[]")

        lines = [
            "---",
            f"jobmail_id: {app['id']}",
            f"company: {_yaml_str(app['company'])}",
            f"role: {_yaml_str(app['role'])}",
            f"stage: {app['stage']}",
            f"applied: {_fmt_d(app['applied_at'])}",
            f"last_activity: {_fmt_d(app['last_activity_at'])}",
            f"closed: {_fmt_d(app['closed_at'])}",
            f"domains: [{', '.join(domains)}]",
            "tags: [job-application]",
            "---",
            "",
            f"# {app['company']}" + (f" — {app['role']}" if app['role'] else ""),
            "",
            f"**Stage:** {app['stage']}  ",
            f"**Applied:** {_fmt_d(app['applied_at'])}  ",
            f"**Last activity:** {_fmt_dt(app['last_activity_at'])}  ",
        ]
        if app["next_action"]:
            lines.append(f"**Next action:** {app['next_action']}" + (f" (due {_fmt_d(app['next_action_due'])})" if app['next_action_due'] else "") + "  ")

        if dates:
            lines += ["", "## Key dates", ""]
            for d in dates:
                lines.append(f"- {_fmt_dt(d['date'])} — {d['description']}")

        lines += ["", "## Timeline", ""]
        for e in events:
            lines.append(f"- {_fmt_dt(e['at'])} · {e['kind']}: {e['detail']}")

        lines += ["", "## Correspondence", ""]
        for m in msgs:
            arrow = "←" if m["direction"] == "inbound" else "→"
            who = m["from_name"] or m["from_addr"] or ""
            flag = " **[needs reply]**" if (m["needs_reply"] and not m["replied_at"]) else ""
            lines.append(f"### {_fmt_dt(m['sent_at'])} {arrow} {who}{flag}")
            lines.append("")
            lines.append(f"**Subject:** {m['subject'] or '(no subject)'}  ")
            if m["message_type"]:
                lines.append(f"**Type:** {m['message_type']}  ")
            if m["summary"]:
                lines.append(f"**Summary:** {m['summary']}  ")
            if m["action_needed"]:
                lines.append(f"**Action:** {m['action_needed']}  ")
            body = (m["body_text"] or "").strip()
            if body:
                snippet = body if len(body) <= 1500 else body[:1500] + " …"
                lines.append("")
                lines.append("> " + snippet.replace("\n", "\n> "))
            lines.append("")

        lines += [MARKER, "", "## My notes", ""]
        return "\n".join(lines) + "\n"

    # --------------------------------------------------------------- write
    def write_application(self, db: Database, app_id: int) -> Path:
        self._ensure_dir()
        app = db.get_application(app_id)
        assert app is not None
        path = self.note_path(app_id, app["company"], app["role"])
        generated = self.render_application(db, app_id)
        user_section = ""
        if path.exists():
            existing = path.read_text(encoding="utf-8")
            if MARKER in existing:
                user_section = existing.split(MARKER, 1)[1]
        if user_section.strip():
            content = generated.split(MARKER, 1)[0] + MARKER + user_section
        else:
            content = generated
        path.write_text(content, encoding="utf-8")
        return path

    def write_index(self, db: Database) -> Path:
        self._ensure_dir()
        apps = db.list_applications()
        by_stage: dict[str, list] = {s: [] for s in STAGES}
        for a in apps:
            by_stage.setdefault(a["stage"], []).append(a)
        lines = ["# Job applications", "", f"_Updated {datetime.now().strftime('%Y-%m-%d %H:%M')} by jobmail._", ""]
        for stage in STAGES:
            rows = by_stage.get(stage) or []
            if not rows:
                continue
            lines += [f"## {stage.title()} ({len(rows)})", ""]
            for a in rows:
                note = self.note_path(int(a["id"]), a["company"], a["role"]).stem
                lines.append(f"- [[{note}]] — last activity {_fmt_d(a['last_activity_at'])}")
            lines.append("")
        path = self.dir / INDEX_NAME
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return path
